"""Adds upvote and downvote to Pitches

Revision ID: 17e92dd2e883
Revises: 5f4384b8f4bd
Create Date: 2020-05-03 23:58:45.989380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e92dd2e883'
down_revision = '5f4384b8f4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('down_votes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('up_votes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('pitches', 'up_votes')
    op.drop_column('pitches', 'down_votes')
    # ### end Alembic commands ###
